{% set name = "novas" %}
{% set version = "3.1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 196191ec67d088357342c88824286273fb1a5dfc96210a4f5e587aabc23d50a5

build:
  skip: true  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - novas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/novas/
  summary: 'NOVAS is an integrated package of functions for computing various commonly needed quantities in positional astronomy.'
  license: LicenseRef-USNO-PD
  license_family: PUBLIC-DOMAIN
  license_file: {{ environ.RECIPE_DIR }}/LICENSE
  description: |
    NOVAS is an integrated package of functions for computing various commonly needed quantities in positional astronomy. The package can supply, in one or two function calls, the instantaneous coordinates of any star or solar system body in a variety of coordinate systems. At a lower level, NOVAS also provides astrometric utility transformations, such as those for precession, nutation, aberration, parallax, and gravitational deflection of light. The computations are accurate to better than one milliarcsecond. The NOVAS library is an easy-to-use facility that can be incorporated into data reduction programs, telescope control systems, and simulations. The U.S. parts of The Astronomical Almanac are prepared using NOVAS.
  doc_url: https://github.com/brandon-rhodes/python-novas/raw/master/Cdist/NOVAS_C3.1_Guide.pdf
  dev_url: https://github.com/brandon-rhodes/python-novas

extra:
  recipe-maintainers:
    - treloar
